name: test1 workflow
on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "started workflow"
          echo "${{ vars.SONAR_HOST_URL }}"
          
